# Wechat auth config.
Wechat:
  appid: wxa5e84ef1c0f19775
  secret: 1e24f049d8e8cb3e7a2456d974269053
  session:
    url: "https://api.weixin.qq.com/sns/jscode2session?"
redis:
  url: 140.143.207.177:6379